-- AlterTable
ALTER TABLE "Property" ADD COLUMN     "address" TEXT,
ADD COLUMN     "availableUnits" INTEGER,
ADD COLUMN     "bookingAmount" TEXT,
ADD COLUMN     "configurations" TEXT[],
ADD COLUMN     "developer" TEXT,
ADD COLUMN     "developerUsp" TEXT,
ADD COLUMN     "floors" INTEGER,
ADD COLUMN     "landArea" TEXT,
ADD COLUMN     "launchDate" TEXT,
ADD COLUMN     "nearbyHospitals" TEXT[],
ADD COLUMN     "nearbyLandmarks" TEXT[],
ADD COLUMN     "nearbyMalls" TEXT[],
ADD COLUMN     "nearbySchools" TEXT[],
ADD COLUMN     "openSpace" TEXT,
ADD COLUMN     "possessionDate" TEXT,
ADD COLUMN     "pricePerSqftMax" INTEGER,
ADD COLUMN     "pricePerSqftMin" INTEGER,
ADD COLUMN     "projectUsp" TEXT[],
ADD COLUMN     "rentalYield" TEXT,
ADD COLUMN     "reraApproved" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "totalUnits" INTEGER,
ADD COLUMN     "towers" INTEGER;
